# Use for finding fingerprints: ~$ codeclimate analyze -f json
---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
      - 58615c6fdff570de9ee174210712ab69
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    exclude_fingerprints:
      - 81f1db8cc66fe7d124f1ecde5904b4e5
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- test/
- vendor/
- .idea/
- client/node_modules/
- app/assets/webpack/
- coverage/
